### ISSUE TITLE
onSaved: (value)  not working

### ISSUE THREAD

**Issue by abdulpiksi** [hiddencaliber/flutter_multiselect#1]
`onSaved: (value) {
              print('The value is $value');
            }`

not working

**Comment by hiddencaliber** [comment]
@abdulpiksi . Thanks for reporting this.

Please check updated example -
https://github.com/hiddencaliber/flutter_multiselect/blob/master/example/lib/main.dart

**Comment by abdulpiksi** [comment]
thanks

**Comment by imasif** [comment]
sorry I can't still make it work, don't see any differences
