### ISSUE TITLE
Limit the number of selected values

### ISSUE THREAD

**Issue by alessandrobelli** [hiddencaliber/flutter_multiselect#12]
Hello!
I need to limit the number of selectable values while the user is in the selection screen, is there a way?

I know there's the validation rule, but as far as I tested, that apply only on form submit...

**Comment by hiddencaliber** [comment]
@alessandrobelli Thanks for the suggestion and code for adding more feature.
I took your advice and added "maxLength" for this. Please check the updated code. I will push the new package tonight.
