### ISSUE TITLE
Provide images or gifs about the package

### ISSUE THREAD

**Issue by irvine5k** [hiddencaliber/flutter_multiselect#15]
Hi, it'll nice to see somes images or a gif in this repo and pub.dev.

**Comment by hiddencaliber** [comment]
@irvine5k , this is done here in github. I will update the package soon in https://pub.dev.

Thanks for the suggestion.

**Comment by irvine5k** [comment]
Great work!

Em seg, 28 de out de 2019 às 14:12, hiddencaliber <notifications@github.com>
escreveu:
