### ISSUE TITLE
Onsaved is not working

### ISSUE THREAD

**Issue by Chuvantinh** [hiddencaliber/flutter_multiselect#19]
I can not get the value of select when I clicked save. The result was printed inner function return InkWell()

**Comment by hiddencaliber** [comment]
@Chuvantinh Please provide code snippet for same.
Thanks,

**Comment by Chuvantinh** [comment]
Pls help me 
I have a form inside of Dialog. There,I have integrated a multi select . The Multiselect worked but I can not get value of the select. 
Hier is function showDialog.

`_showAddDialog() {
    showDialog(
        context: context,
        builder: (context) => AlertDialog(
              content: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                  TextFormField(
                  validator: (value) {
                      if (value.isEmpty) {
                        return 'Please enter some text';
                      }
                        return null;
                      },
                    decoration: InputDecoration(labelText: 'Medikament Name *'),
                    controller: name_medical,
                ),
                  SizedBox(height: 20),
                    TextFormField(
                      validator: (value) {
                        if (value.isEmpty) {
                          return 'Please enter some text';
                        }
                        return null;
                      },
                    decoration: InputDecoration(labelText: 'Dosage *'),
                    controller: dosage,
                  ),
                  SizedBox(height: 20),
                    TextFormField(
                    decoration: InputDecoration(labelText: 'Note'),
                    controller: note,
                  ),

                    Container(
                      margin: new EdgeInsets.only(left: 0,top: 15.0,right: 0, bottom: 15.0),
                      child: MultiSelect(
                          autovalidate: false,
                          titleText: "Select",
                          validator: (value) {
                            if (value == null) {
                              return 'Please select one or more option(s)';
                            }
                          },
                          errorText: 'Please select one or more option(s)',
                          dataSource: [
                            {
                              "display": "9 Uhr",
                              "value": 9,
                            },
                            {
                              "display": "12 Uhr",
                              "value": 12,
                            },
                            {
                              "display": "18 Uhr",
                              "value": 18,
                            },
                            {
                              "display": "21 Uhr",
                              "value": 21,
                            }
                          ],
                          textField: 'display',
                          valueField: 'value',
                          filterable: true,
                          required: true,
                          value: _myclock,
                          onSaved: (value) {
                            //print('The value is $value');
                            setState(() {
                              _myclock = value;
                            });
                          }
                      ),
                    ),
                  Container(
                    margin: new EdgeInsets.symmetric(horizontal: 80.0),
                    child:FlatButton(
                      color: Colors.teal,
                      child: Text("Save",
                        style: TextStyle(
                            color: Colors.white
                        ),),
                      onPressed: () {
                        print(_myclock);
                        if(_formKey.currentState.validate()){
                          if(note.text != null){
                            _eventController.text = name_medical.text + "-- " + dosage.text + "--" + note.text;
                          }else{
                            _eventController.text = name_medical.text + "--" + dosage.text;
                          }

                          if(_eventController.text != null && _eventController.text != ""){
                            setState(() {
                              if (_events[_controller.selectedDay] != null) {
                                _events[_controller.selectedDay].add(_eventController.text);
                              } else {
                                _events[_controller.selectedDay] = [
                                  _eventController.text
                                ];
                              }
                              prefs.setString("events", json.encode(encodeMap(_events)));
                              _eventController.clear();
                              Navigator.pop(context);
                            });
                            name_medical.clear();
                            dosage.clear();
                            note.clear();
                          }
                        }

                      },
                    )
                  ),
                ],
              )
              ))
    );
  }`

**Comment by Chuvantinh** [comment]
Sorry about the code, but I can not put the code in the comment. Something is wrong on Github

**Comment by Chuvantinh** [comment]
I have posted code in this website 

https://codepen.io/chu-vn-t-nh/pen/JjoMoQE

**Comment by hiddencaliber** [comment]
@Chuvantinh you need to call form's save method after you validate it.

For eg. here
if (_formKey.currentState.validate()) {
   **_formKey.currentState.save();**
   if (note.text != null) {

**Comment by Chuvantinh** [comment]
Yes I have done it  on the line 88 . and on the line 89 I print my value on select but It is always null or []. when I print (print(_myclock);)

ON the line 73 : I do not taken any thing from function onSaved () . 

Can you pls help me more ? 
hier is the code : https://codepen.io/chu-vn-t-nh/pen/JjoMoQE

**Comment by hiddencaliber** [comment]
@Chuvantinh : You need to call _formKey.currentState.save();, like I said before.
onSaved is only called when the form save is triggered

**Comment by Chuvantinh** [comment]
I didn't read your comment carefully before. 
Thanks I got it , thank you very much.
I close this post .
