### ISSUE TITLE
Eliminate hardcoded colors, looks partially unreadable with dark theme.

### ISSUE THREAD

**Issue by slavap** [hiddencaliber/flutter_multiselect#22]
![image](https://user-images.githubusercontent.com/4129763/72407964-2a7f1080-3716-11ea-9a17-4941716e9038.png)

**Comment by hiddencaliber** [comment]
@slavap I will make this change. Thanks for testing this with dark theme.

**Comment by Zeeshan0201** [comment]
@hiddencaliber have you added support for black theme? getting same issue as mentioned above..

**Comment by hiddencaliber** [comment]
@Zeeshan0201 : Not yet, I am planning to push that change in next 2-3 days. Thanks for showing your interest in this plugin.

**Comment by hiddencaliber** [comment]
@slavap @Zeeshan0201 : Please check version 0.5.0. 
I have added more options for better control. Enjoy!

**Comment by slavap** [comment]
@hiddencaliber Thank you! Actually I've expected that default look and feel will be fixed for dark theme as well, so no need to customize and could be used right out of box. But I don't mind to do that by myself, I have needed properties now :-)

**Comment by hiddencaliber** [comment]
All,
Please add another one if you have any other issue.
I am closing this one. 
Thanks
